Regex: true
Keywords:
- Keyword: DEBUG
  Color: yellow
- Keyword: ERROR
  Color: red
- Keyword: "FAIL:"
  Color: red
- Keyword: ^FAIL
  Color: red
- Keyword: FATAL
  Color: red
- Keyword: "OK:"
  Color: green
- Keyword: ^ok(\s|\xA0)+
  Color: green
- Keyword: PASS
  Color: green
- Keyword: INFO
  Color: green
- Keyword: ^(\s|\xA0)+\+(\s|\xA0)+
  Color: green
- Keyword: ^(\s|\xA0)+-(\s|\xA0)+
  Color: red
- Keyword: ^\?
  Color: gray
- Keyword: ^===(\s|\xA0)+RUN
  Color: cyan
