Keywords:
- Keyword: ERROR
  Color: red
- Keyword: FAIL
  Color: red
- Keyword: FATAL
  Color: red
- Keyword: OK
  Color: green
- Keyword: PASS
  Color: green
- Keyword: INFO
  Color: green
- Keyword: DEBUG
  Color: yellow
